name: publish

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        required: true
        default: 'alpha'
        description: Which type of release
        options:
        - alpha
        - patch
        - minor
        - major
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: |
          npm install && npm run build
          git config user.name github-actions
          git config user.email github-actions@github.com
          VERSION="${{ github.event.inputs.type }}"
          if [ -z "$VERSION" ]; then
            VERSION="alpha"
          fi
          if [ $VERSION = "alpha" ]; then
            npm version prerelease --preid=alpha
            npm publish --tag alpha
          else
            npm version $VERSION
            npm publish --access=public --tag latest
          fi
          git push --follow-tags
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
